### PR TITLE
Improvement for Internet Proxy purpose and JIRA Agile feature

### PR DESCRIPTION
**Pull request by libetl**
Some features in this improv can be useful for developers (i think of people using git and not wanting to type each time the name of their current issue), you can display in one shot the description of your issue along with its parent (if it's a subtask).

Take a look at it, please.
Thank you.

### CODE REVIEW

**Comment by juliangruber** [comment]
i don't have the time to review this at the moment. @plainview what do you think?

**Comment by libetl** [comment]
I forgot to tell you i added a spare method named "status" if you need to change the status of an issue to another value not listed in the commands.

**Comment by ghost** [comment]
Hi libetl, can you split these into separate pull requests?  One for the proxy code and one for the agile work.

I see the immediate need for the proxy code and I think we should merge it but it needs some changes:

When I run `npm install` in your branch, I get the following error:

``` bash
npm ERR! peerinvalid The package superagent does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer superagent-proxy@0.3.0 wants superagent@~0.15.4

npm ERR! System Darwin 13.0.0
npm ERR! command "/Users/scottseaward/.bin/v0.10.22/bin/node" "/Users/scottseaward/.bin/v0.10.22/bin/npm" "install"
npm ERR! cwd /Users/scottseaward/Code/js/jilla
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/scottseaward/Code/js/jilla/npm-debug.log
npm ERR! not ok code 0
```

Please update the superagent version in package.json.

We need to keep the Jira URL, Username, and Password as the first config options when you run `jilla config`.  They're the required fields and should go first.

I'm happy to look over the agile work in a separate PR.  My immediate thoughts are that the gira command is a shell script, which limits its use to BASH variants.  It's also very specific to a single JIRA workflow.  I'm not convinced it should be included as part of jilla.  I'll look at the rest in detail in the PR.

**Comment by libetl** [comment]
going to make another pull request for proxy only

**Comment by libetl** [comment]
Done.
I made another PR which concerns only proxying.

2014/1/24 Scott Seaward notifications@github.com

> Hi libetl, can you split these into separate pull requests? One for the
> proxy code and one for the agile work.
> 
> I see the immediate need for the proxy code and I think we should merge it
> but it needs some changes:
> 
> When I run npm install in your branch, I get the following error:
> 
> npm ERR! peerinvalid The package superagent does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer superagent-proxy@0.3.0 wants superagent@~0.15.4
> 
> npm ERR! System Darwin 13.0.0
> npm ERR! command "/Users/scottseaward/.bin/v0.10.22/bin/node" "/Users/scottseaward/.bin/v0.10.22/bin/npm" "install"
> npm ERR! cwd /Users/scottseaward/Code/js/jilla
> npm ERR! node -v v0.10.22
> npm ERR! npm -v 1.3.14
> npm ERR! code EPEERINVALID
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!     /Users/scottseaward/Code/js/jilla/npm-debug.log
> npm ERR! not ok code 0
> 
> Please update the superagent version in package.json.
> 
> We need to keep the Jira URL, Username, and Password as the first config
> options when you run jilla config. They're the required fields and should
> go first.
> 
> I'm happy to look over the agile work in a separate PR. My immediate
> thoughts are that the gira command is a shell script, which limits its use
> to BASH variants. It's also very specific to a single JIRA workflow. I'm
> not convinced it should be included as part of jilla. I'll look at the rest
> in detail in the PR.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/godmodelabs/jilla/pull/10#issuecomment-33237601
> .

## 

Lionel Ben Ychou
 15 Ter Rue Roger Salengro
 92120 Montrouge
 Hauts-de-Seine, Île-de-France
 France

 Tel : +33 (0) 6 51 86 38 21

**Pull request closed without merging**
